export type CountryCode = "MR" | "MA" | "DZ" | "TN" | "LY";

export const COUNTRY_OPTIONS: Array<{ value: CountryCode; label: string; flag: string }> = [
  { value: "MR", label: "Mauritanie", flag: "🇲🇷" },
  { value: "MA", label: "Maroc", flag: "🇲🇦" },
  { value: "DZ", label: "Algérie", flag: "🇩🇿" },
  { value: "TN", label: "Tunisie", flag: "🇹🇳" },
  { value: "LY", label: "Libye", flag: "🇱🇾" },
];

export const REGION_OPTIONS: Record<string, string[]> = {
  MR: [
    "Nouakchott",
    "Adrar",
    "Assaba",
    "Brakna",
    "Gorgol",
    "Guidimakha",
    "Hodh El Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Moughataa",
    "Nema",
    "Nouadhibou",
    "Tagant",
    "Tidjikja",
    "Tiris Zemmour",
    "Zouerate",
  ],
  MA: [
    "Casablanca-Settat",
    "Rabat-Salé-Kénitra",
    "Tanger-Tétouan-Al Hoceima",
    "Fès-Meknès",
    "L'Oriental",
    "Marrakech-Safi",
    "Sous-Massa",
    "Beni-Mellal-Khénifra",
    "Draa-Tafilalt",
    "Laayoune-Sakiat al Hamra",
    "Guelmim-Oued Noun",
    "Ed Dakhla-Oued Ed Dahab",
  ],
  DZ: [
    "Adrar (01)",
    "Chlef (02)",
    "Laghouat (03)",
    "Oum El Bouaghi (04)",
    "Batna (05)",
    "Bejaia (06)",
    "Biskra (07)",
    "Béchar (08)",
    "Blida (09)",
    "Bouira (10)",
    "Tamanrasset (11)",
    "Tébessa (12)",
    "Tlemcen (13)",
    "Tiaret (14)",
    "Tizi-Ouzou (15)",
    "Alger (16)",
    "Djelfa (17)",
    "Jijel (18)",
    "Sétif (19)",
    "Saida (20)",
    "Skikda (21)",
    "Sidi Bel Abbes (22)",
    "Annaba (23)",
    "Guelma (24)",
    "Constantine (25)",
    "Médéa (26)",
    "Mostaganem (27)",
    "M'Sila (28)",
    "Mascara (29)",
    "Ouargla (30)",
    "Oran (31)",
    "El Bayadh (32)",
    "Illizi (33)",
    "Bordj Bou Arreridj (34)",
    "Boumerdes (35)",
    "El Tarf (36)",
    "Tindouf (37)",
    "Tissemsilt (38)",
    "El Oued (39)",
    "Khenchela (40)",
    "Souk Ahras (41)",
    "Tipaza (42)",
    "Mila (43)",
    "Ain Defla (44)",
    "Naama (45)",
    "Ain Temouchent (46)",
    "Ghardaïa (47)",
    "Relizane (48)",
    "Timimoune (49)",
    "Bordj Badji Mokhtar (50)",
    "Ouled Djellal (51)",
    "Béni Abbès (52)",
    "Ain Salah (53)",
    "In Guezzam (54)",
    "Touggourt (55)",
    "Djanet (56)",
    "El Meghaier (57)",
    "El Menia (58)",
    "Aflou (59)",
    "El Abiodh Sidi Cheikh (60)",
    "El Aricha (61)",
    "El Kantara (62)",
    "Barika (63)",
    "Bou Saada (64)",
    "Bir El Ater (65)",
    "Ksar El Boukhari (66)",
    "Ksar Chellala (67)",
    "Ain Oussara (68)",
    "Messaad (69)",
  ],
  TN: [
    "Ariana",
    "Ben Arous",
    "Bizerte",
    "Beja",
    "Gabes",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kebili",
    "La Manouba",
    "Le Kef",
    "Mahdia",
    "Monastir",
    "Mednine",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan",
  ],
  LY: [
    "Al Jabal al Akhdar",
    "Al Jufrah",
    "Al Kufrah",
    "Al Marj",
    "Al Marqab",
    "An Nuqat Al Khams",
    "Ash Shati",
    "Az Zawiyah",
    "Benghazi",
    "Darnah",
    "Jabal Al Gharbi",
    "Misratah",
    "Murzuq",
    "Sabha",
    "Sha Biyat Al Butnan",
    "Sha Biyat Al Jafarah",
    "Sha Biyat Al Wahat",
    "Sha Biyat Ghat",
    "Sha Biyat Nalut",
    "Sha Biyat Al Hayat",
    "Surt",
    "Tripoli",
  ],
};
