COUNTRY_REGIONS = [
    {
        "code": "MR",
        "label": "Mauritanie",
        "regions": [
            "Nouakchott",
            "Adrar",
            "Assaba",
            "Brakna",
            "Gorgol",
            "Guidimakha",
            "Hodh El Chargui",
            "Hodh El Gharbi",
            "Inchiri",
            "Moughataa",
            "Néma",
            "Nouadhibou",
            "Tagant",
            "Tidjikja",
            "Tiris Zemmour",
            "Zouerate",
        ],
    },
    {
        "code": "MA",
        "label": "Maroc",
        "regions": [
            "Casablanca-Settat",
            "Rabat-Salé-Kénitra",
            "Tanger-Tétouan-Al Hoceïma",
            "Fès-Meknès",
            "L'Oriental",
            "Marrakech-Safi",
            "Sous-Massa",
            "Béni-Mellal-Khénifra",
            "Drâa-Tafilalet",
            "Laâyoune-Sakia El Hamra",
            "Guelmim-Oued Noun",
            "Dakhla-Oued Ed Dahab",
        ],
    },
    {
        "code": "DZ",
        "label": "Algérie",
        "regions": [
            "Adrar 01",
            "Chlef 02",
            "Laghouat 03",
            "Oum El Bouaghi 04",
            "Batna 05",
            "Bejaia 06",
            "Biskra 07",
            "Béchar 08",
            "Blida 09",
            "Bouira 10",
            "Tamanrasset 11",
            "Tébessa 12",
            "Tlemcen 13",
            "Tiaret 14",
            "Tizi-Ouzou 15",
            "Alger 16",
            "Djelfa 17",
            "Jijel 18",
            "Sétif 19",
            "Saïda 20",
            "Skikda 21",
            "Sidi Bel Abbès 22",
            "Annaba 23",
            "Guelma 24",
            "Constantine 25",
            "Médéa 26",
            "Mostaganem 27",
            "M'Sila 28",
            "Mascara 29",
            "Ouargla 30",
            "Oran 31",
            "El Bayadh 32",
            "Illizi 33",
            "Bordj Bou Arréridj 34",
            "Boumerdès 35",
            "El Tarf 36",
            "Tindouf 37",
            "Tissemsilt 38",
            "El Oued 39",
            "Khenchela 40",
            "Souk Ahras 41",
            "Tipaza 42",
            "Mila 43",
            "Aïn Defla 44",
            "Naâma 45",
            "Aïn Témouchent 46",
            "Ghardaïa 47",
            "Relizane 48",
            "Timimoun 49",
            "Bordj Badji Mokhtar 50",
            "Ouled Djellal 51",
            "Béni Abbès 52",
            "Aïn Salah 53",
            "In Guezzam 54",
            "Touggourt 55",
            "Djanet 56",
            "El Meghaier 57",
            "El Menia 58",
            "Aflou 59",
            "El Abiodh Sidi Cheikh 60",
            "El Aricha 61",
            "El Kantara 62",
            "Barika 63",
            "Bou Saâda 64",
            "Bir El Ater 65",
            "Ksar El Boukhari 66",
            "Ksar Chellala 67",
            "Aïn Oussara 68",
            "Messaad 69",
        ],
    },
    {
        "code": "TN",
        "label": "Tunisie",
        "regions": [
            "Ariana",
            "Ben Arous",
            "Bizerte",
            "Béja",
            "Gabès",
            "Gafsa",
            "Jendouba",
            "Kairouan",
            "Kasserine",
            "Kébili",
            "La Manouba",
            "Le Kef",
            "Mahdia",
            "Monastir",
            "Médenine",
            "Nabeul",
            "Sfax",
            "Sidi Bouzid",
            "Siliana",
            "Sousse",
            "Tataouine",
            "Tozeur",
            "Tunis",
            "Zaghouan",
        ],
    },
    {
        "code": "LY",
        "label": "Libye",
        "regions": [
            "Al Djabal Al Akhdar",
            "Al Jufrah",
            "Al Kufrah",
            "Al Marj",
            "Al Marqab",
            "An Nuqat Al Khams",
            "Ash Shati",
            "Az Zawiyah",
            "Benghazi",
            "Darnah",
            "Jabal Al Gharbi",
            "Misratah",
            "Murzuq",
            "Sabha",
            "Sha'biyat Al Butnan",
            "Sha'biyat Al Jafarah",
            "Sha'biyat Al Wahat",
            "Sha'biyat Ghat",
            "Sha'biyat Nalut",
            "Sha'biyat Al Hayat",
            "Surt",
            "Tripoli",
        ],
    },
]

COUNTRY_CITIES = {
    "MR": [
        "Nouakchott",
        "Nouadhibou",
        "Rosso",
        "Atar",
        "Aioun el Atrouss",
        "Kiffa",
        "Kaédi",
        "Tidjikja",
    ],
    "MA": [
        "Casablanca",
        "Rabat",
        "Marrakech",
        "Fès",
        "Tanger",
        "Agadir",
        "Meknès",
        "Oujda",
        "Laâyoune",
        "Dakhla",
    ],
    "DZ": [
        "Alger",
        "Oran",
        "Constantine",
        "Annaba",
        "Blida",
        "Tlemcen",
        "Biskra",
        "Ghardaïa",
        "Tamanrasset",
        "Sétif",
    ],
    "TN": [
        "Tunis",
        "Sfax",
        "Sousse",
        "Kairouan",
        "Gabès",
        "Bizerte",
        "Nabeul",
        "Gafsa",
        "Monastir",
        "Mahdia",
    ],
    "LY": [
        "Tripoli",
        "Benghazi",
        "Misratah",
        "Az Zawiyah",
        "Sabha",
        "Surt",
        "Darnah",
        "Al Bayda",
        "Gharyan",
        "Murzuq",
    ],
}

LISTING_CATEGORIES = [
    {
        "slug": "immobilier",
        "title": "Immobilier",
        "description": "Appartements, villas, terrains et locaux commerciaux.",
    },
    {
        "slug": "vehicules",
        "title": "Véhicules",
        "description": "Voitures import, 4x4 désert, motos et mobilité douce.",
    },
    {
        "slug": "emploi",
        "title": "Emploi & Services",
        "description": "Talents tech, artisans, missions freelances et CDI.",
    },
    {
        "slug": "market",
        "title": "Marché local",
        "description": "Artisanat, produits du terroir et électronique reconditionnée.",
    },
]

CATEGORY_FIELD_SCHEMAS = {
    "vehicules": [
        {"name": "mileage", "type": "number", "required": False},
        {"name": "fuel", "type": "choice", "choices": ["diesel", "essence", "hybride", "electrique"]},
        {"name": "transmission", "type": "choice", "choices": ["auto", "manuelle"]},
    ],
    "immobilier": [
        {"name": "surface", "type": "number", "required": True},
        {"name": "rooms", "type": "number", "required": True},
        {"name": "property_type", "type": "choice", "choices": ["appartement", "villa", "bureau", "terrain"]},
    ],
    "services": [
        {"name": "service_area", "type": "text"},
        {"name": "experience", "type": "text"},
    ],
    "emploi": [
        {"name": "contract_type", "type": "choice", "choices": ["cdi", "cdd", "freelance", "stage"]},
        {"name": "experience_level", "type": "choice", "choices": ["junior", "intermediaire", "senior"]},
    ],
}
