# Generated by Django 6.0.3 on 2026-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_attributes_listing_auto_moderation_flags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cover_image',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
