# Generated by Django 6.0.3 on 2026-03-30 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cover_image',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
