# Generated by Django 6.0.3 on 2026-03-30 17:58

import listings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cover_image',
            field=models.TextField(blank=True, validators=[listings.validators.validate_cover_image_reference]),
        ),
    ]
